# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0002_networthvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networthvalue',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
