# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntmeta', '0003_auto_20170407_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
