# Generated by Django 2.0.4 on 2018-04-20 19:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ntgame.models.effect


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ntmeta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.IntegerField()),
                ('expires_at', models.IntegerField(default=None)),
                ('applies_at', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('diminishing_return', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tag', models.CharField(max_length=40, unique=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntmeta.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.IntegerField(default=400)),
                ('explored', models.IntegerField(default=0)),
                ('built', models.IntegerField(default=0)),
                ('province', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ntgame.Province')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Building')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.IntegerField(choices=[('DELAYED', ntgame.models.effect.EffectType(1)), ('IMMEDIATE', ntgame.models.effect.EffectType(2)), ('OVER_TIME', ntgame.models.effect.EffectType(3)), ('NEXT_TURN', ntgame.models.effect.EffectType(4))], default=ntgame.models.effect.EffectType(2))),
                ('duration', models.IntegerField(default=1)),
                ('magnitude', models.FloatField(default=0.0)),
                ('base_value', models.IntegerField(default=None)),
                ('base_is_min', models.BooleanField(default=False)),
                ('is_negative', models.BooleanField(default=False)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('island', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldiers', models.IntegerField(default=0)),
                ('offspec', models.IntegerField(default=0)),
                ('defspec', models.IntegerField(default=0)),
                ('elites', models.IntegerField(default=0)),
                ('thieves', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Province Name')),
                ('ruler', models.CharField(max_length=60, verbose_name='Ruler Name')),
                ('peasants', models.IntegerField(default=1000)),
                ('money', models.IntegerField(default=10000)),
                ('land', models.IntegerField(default=500)),
                ('food', models.IntegerField(default=8000)),
                ('mages', models.IntegerField(default=0)),
                ('runes', models.IntegerField(default=0)),
                ('warhorses', models.IntegerField(default=0)),
                ('prisoners', models.IntegerField(default=0)),
                ('trade_balance', models.IntegerField(default=0)),
                ('kingdom', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Kingdom')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('offense_spec_name', models.CharField(default='Off. Spec', max_length=40)),
                ('defensive_spec_name', models.CharField(default='Def. Spec', max_length=40)),
                ('elite_name', models.CharField(default='Elite', max_length=40)),
                ('offense_spec_value', models.IntegerField(default=4)),
                ('defense_spec_value', models.IntegerField(default=4)),
                ('elite_offense', models.IntegerField(default=0)),
                ('elite_defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('variable_range', models.IntegerField(default=0)),
                ('difficulty', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('effect_instance', models.ManyToManyField(to='ntgame.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Race'),
        ),
        migrations.AddField(
            model_name='military',
            name='province',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AddField(
            model_name='building',
            name='effect_instance',
            field=models.ManyToManyField(to='ntgame.Instance'),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by', to='ntgame.Province'),
        ),
        migrations.AddField(
            model_name='application',
            name='applied_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to='ntgame.Province'),
        ),
        migrations.AddField(
            model_name='application',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Instance'),
        ),
    ]
