# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-09 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('island', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Province Name')),
                ('race', models.CharField(max_length=40, verbose_name='Province Race')),
                ('kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Kingdom')),
            ],
        ),
    ]
