# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=40)),
                ('soldiers', models.IntegerField()),
                ('offspec', models.IntegerField()),
                ('defspec', models.IntegerField()),
                ('elites', models.IntegerField()),
                ('thieves', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='province',
            name='food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='land',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='mages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='peasants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='prisoners',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='ruler',
            field=models.CharField(default='Nameless', max_length=60, verbose_name='Ruler Name'),
        ),
        migrations.AddField(
            model_name='province',
            name='runes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='trade_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='province',
            name='warhorses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='province',
            name='kingdom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Kingdom'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(default='Unknown', max_length=200, verbose_name='Province Name'),
        ),
        migrations.AlterField(
            model_name='province',
            name='race',
            field=models.CharField(default='Human', max_length=40, verbose_name='Province Race'),
        ),
        migrations.AddField(
            model_name='province',
            name='army',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Army'),
        ),
    ]
