# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0002_auto_20161129_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('offense_spec_value', models.IntegerField(default=4)),
                ('defense_spec_value', models.IntegerField(default=4)),
                ('elite_offense', models.IntegerField(default=0)),
                ('elite_defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='army',
            name='race',
        ),
        migrations.AlterField(
            model_name='province',
            name='army',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Army'),
        ),
        migrations.AlterField(
            model_name='province',
            name='kingdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Kingdom'),
        ),
        migrations.AlterField(
            model_name='province',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Race'),
        ),
    ]
