# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0006_rule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
