# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0007_delete_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='defensive_spec_name',
            field=models.CharField(default='Def. Spec', max_length=40),
        ),
        migrations.AddField(
            model_name='race',
            name='offense_spec_name',
            field=models.CharField(default='Off. Spec', max_length=40),
        ),
    ]
