# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0008_auto_20170407_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='elite_name',
            field=models.CharField(default='Elite', max_length=40),
        ),
    ]
