# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0009_race_elite_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='defspec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='army',
            name='elites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='army',
            name='offspec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='army',
            name='soldiers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='army',
            name='thieves',
            field=models.IntegerField(default=0),
        ),
    ]
