# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0010_auto_20170407_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldiers', models.IntegerField(default=0)),
                ('offspec', models.IntegerField(default=0)),
                ('defspec', models.IntegerField(default=0)),
                ('elites', models.IntegerField(default=0)),
                ('thieves', models.IntegerField(default=0)),
            ],
        )
    ]
