# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0012_auto_20170407_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='id',
        ),
        migrations.AlterField(
            model_name='province',
            name='military',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ntgame.Military'),
        )
    ]
