# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0013_auto_20170407_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='province',
            name='military',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Military'),
        ),
    ]
