# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0014_auto_20170407_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='army',
        ),
        migrations.AlterField(
            model_name='province',
            name='food',
            field=models.IntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='province',
            name='land',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='province',
            name='money',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='province',
            name='peasants',
            field=models.IntegerField(default=1000),
        ),
        migrations.DeleteModel(
            name='Army',
        ),
    ]
