# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ntgame', '0015_auto_20170407_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Province Name'),
        ),
        migrations.AlterField(
            model_name='province',
            name='ruler',
            field=models.CharField(max_length=60, verbose_name='Ruler Name'),
        ),
    ]
