# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0016_auto_20170503_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='borrower',
            new_name='owner',
        ),
    ]
