# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 00:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0017_auto_20170503_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('magnitude', models.IntegerField()),
                ('diminishing_ratio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('tag', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.IntegerField()),
                ('explored', models.IntegerField()),
                ('built', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Building')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Infrastructure')),
            ],
        ),
        migrations.AlterField(
            model_name='province',
            name='kingdom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Kingdom'),
        ),
        migrations.AlterField(
            model_name='province',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='building',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Effect'),
        ),
        migrations.AddField(
            model_name='province',
            name='infrastructure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ntgame.Infrastructure'),
        ),
    ]
