# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0018_auto_20170528_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='infrastructure',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='province',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='built',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='explored',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='land',
            field=models.IntegerField(default=400),
        ),
    ]
