# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-29 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0019_auto_20170529_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
    ]
