# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0020_auto_20170529_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='military',
        ),
        migrations.AddField(
            model_name='military',
            name='province',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='province',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='ntgame.Province'),
        ),
    ]
