# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0021_auto_20170529_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='etype',
            field=models.IntegerField(choices=[(1, 'immediate'), (2, 'each_round'), (3, 'one_round'), (4, 'on_expire')], default=1),
        ),
    ]
