# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0023_auto_20170728_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.IntegerField(choices=[(1, 'immediate'), (2, 'each_round'), (3, 'one_round'), (4, 'on_expire'), (5, 'permanent')], default=1)),
                ('applied_on', models.IntegerField()),
                ('expires_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EffectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='building',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='etype',
        ),
        migrations.AddField(
            model_name='effectinstance',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Effect'),
        ),
        migrations.AddField(
            model_name='effectapplication',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.EffectInstance'),
        ),
        migrations.AddField(
            model_name='effectapplication',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Province'),
        ),
        migrations.AddField(
            model_name='building',
            name='effecti',
            field=models.ManyToManyField(to='ntgame.EffectInstance'),
        ),
    ]
