# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0024_auto_20170803_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='magnitude',
        ),
    ]
