# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0025_remove_building_magnitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='effecti',
            new_name='effect_instance',
        ),
    ]
