# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ntgame', '0026_auto_20170803_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingEffectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magnitude', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='effectinstance',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='building',
            name='effect_instance',
        ),
        migrations.RemoveField(
            model_name='effectapplication',
            name='instance',
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.DeleteModel(
            name='EffectInstance',
        ),
        migrations.AddField(
            model_name='buildingeffectinstance',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.Building'),
        ),
        migrations.AddField(
            model_name='buildingeffectinstance',
            name='effect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ntgame.Effect'),
        ),
        migrations.AddField(
            model_name='effectapplication',
            name='building_effecti',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ntgame.BuildingEffectInstance'),
        ),
    ]
